# -*- coding: utf-8 -*-
"""videogame.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WCOmzLZgDUAft-uCQHVuuAq52T9INWpY
"""

import pandas as pd
import numpy as np

games = pd.read_csv("games.csv")
sales = pd.read_csv("vgsales.csv")

# CLEAN games.csv

# Drop duplicates
games.drop_duplicates(inplace=True)

# Convert Release Date to datetime and extract year
games['Release Date'] = pd.to_datetime(games['Release Date'], errors='coerce')
games['Release_Year'] = games['Release Date'].dt.year

# Function to convert string numbers like "1.2K" or "3M" → numeric
def parse_number(x):
    if isinstance(x, str):
        x = x.strip().replace(',', '').upper()
        if 'K' in x:
            return float(x.replace('K','')) * 1_000
        elif 'M' in x:
            return float(x.replace('M','')) * 1_000_000
        elif x.isdigit():
            return float(x)
        else:

            return x

# Apply to numeric columns
num_cols = ['Times Listed','Number of Reviews','Plays','Playing','Backlogs','Wishlist']
for col in num_cols:
    if col in games.columns:
        games[col] = games[col].apply(parse_number)

# Fill missing Team and Summary with placeholders
games['Team'] = games['Team'].fillna('Unknown')
games['Summary'] = games['Summary'].fillna('No summary available')
games['Rating'] = games['Rating'].fillna(games['Rating'].mean())
sales['Publisher'] = sales['Publisher'].fillna('Unknown')

# Fill missing Ratings with mean
games['Rating'].fillna(games['Rating'].mean(), inplace=True)

# Clean Genres column (convert list-like strings to comma-separated)
games['Genres'] = games['Genres'].astype(str).str.replace(r"[\[\]\'\"]", '', regex=True)

# Drop unnecessary unnamed column if exists
games.drop(columns=[col for col in games.columns if 'Unnamed' in col], inplace=True)

# CLEAN vgsales.csv

sales.drop_duplicates(inplace=True)
sales['Publisher'].fillna('Unknown', inplace=True)
sales['Year'] = pd.to_numeric(sales['Year'], errors='coerce').fillna(0).astype(int)

# Standardize text casing
sales['Platform'] = sales['Platform'].str.upper()
sales['Genre'] = sales['Genre'].str.title()
sales['Publisher'] = sales['Publisher'].str.title()

# SAVE CLEANED FILES
games.to_csv("games_clean.csv", index=False)
sales.to_csv("vgsales_clean.csv", index=False)

print("✅ Cleaning complete.")
print("games_clean.csv →", games_clean_path)
print("vgsales_clean.csv →", sales_clean_path)

display(games.head(3))
display(sales.head(3))