# -*- coding: utf-8 -*-
"""EDA_Uber.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p8fz-Z1gEXxF-IhCfgpyMn0v7mnnLKNH
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("Uber Request Data.csv")

df['Request timestamp'] = pd.to_datetime(df['Request timestamp'], dayfirst=True, errors='coerce')
df['Drop timestamp'] = pd.to_datetime(df['Drop timestamp'], dayfirst=True, errors='coerce')

df['Request hour'] = df['Request timestamp'].dt.hour
df['Request day'] = df['Request timestamp'].dt.day_name()

df['Driver id'] = df['Driver id'].fillna(-1)

df = df.drop_duplicates()

# ------------------------- VISUALIZATIONS -------------------------


plt.figure(figsize=(10, 5))
sns.countplot(data=df, x='Request hour', palette='viridis')
plt.title('Number of Uber Requests per Hour')
plt.xlabel('Hour of Day')
plt.ylabel('Request Count')
plt.xticks(range(0, 24))
plt.show()

plt.figure(figsize=(8, 5))
sns.countplot(data=df, x='Pickup point', hue='Status', palette='Set2')
plt.title('Status Breakdown by Pickup Point')
plt.xlabel('Pickup Point')
plt.ylabel('Count')
plt.legend(title='Status')
plt.show()

plt.figure(figsize=(10, 5))
sns.countplot(data=df,
              x='Request day',
              order=['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
              palette='coolwarm')
plt.title('Requests by Day of the Week')
plt.xlabel('Day')
plt.ylabel('Request Count')
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(12, 6))
sns.heatmap(df.isnull(), cbar=False, cmap='YlGnBu')
plt.title("Missing Values Heatmap")
plt.show()

plt.figure(figsize=(10, 5))
sns.boxplot(x='Status', y='Request hour', data=df, palette='pastel')
plt.title('Request Hour Distribution by Status')
plt.xlabel('Status')
plt.ylabel('Request Hour')
plt.show()

df['Pickup point'].value_counts().plot(kind='pie',autopct='%1.1f%%', figsize=(5, 5), title='Pickup Point Split')
plt.ylabel("")
plt.show()